# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='الهاتف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('job_title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('salary', models.IntegerField(default=0, verbose_name='الراتب')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extra.user_content_file_name, verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', extra.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=extra.content_file_name, verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(upload_to=extra.content_file_name, verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=200, verbose_name='رقم السيارة')),
                ('car_manu_year', models.IntegerField(default=0, verbose_name='سنة التصنيع')),
                ('car_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السنوية ١')),
                ('car_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السنوية ٢')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ١')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٢')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٣')),
                ('barcode', models.CharField(max_length=200, verbose_name='باركود')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة الباركود')),
                ('balance', models.IntegerField(default=0, verbose_name='الرصيد')),
                ('max_balance', models.IntegerField(default=0, verbose_name='الحد الاقصى للرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='CarSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='واتس اب')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='فيسبوك')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='انستغرام')),
                ('tiktok', models.CharField(blank=True, max_length=200, null=True, verbose_name='تيك توك')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنا')),
                ('privacy', models.CharField(blank=True, max_length=200, null=True, verbose_name='الخصوصية')),
                ('offer_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='وقت العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=200, verbose_name='نوع المستخدم')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='النص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب')], default='mandob', max_length=200, verbose_name='نوع المستخدم')),
                ('pay_type', models.CharField(choices=[('get', 'قبض'), ('pay', 'دفع')], default='get', max_length=200, verbose_name='نوع السند')),
                ('amount', models.IntegerField(default=0, verbose_name='القيمة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم المودل')),
                ('create', models.BooleanField(default=False, verbose_name='انشاء')),
                ('update', models.BooleanField(default=False, verbose_name='تعديل')),
                ('list', models.BooleanField(default=False, verbose_name='عرض')),
                ('delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الكروب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('km_price', models.IntegerField(default=0, verbose_name='سعر الكيلو متر')),
                ('worker_prec', models.FloatField(default=0, verbose_name='نسبة عامل تخصص')),
                ('weight_prec', models.FloatField(default=0, verbose_name='نسبة عامل الوزن')),
                ('company_prec', models.FloatField(default=0, verbose_name='نسبة الشركة')),
                ('can_order_workers', models.BooleanField(default=False, verbose_name='هل يمكنه طلب عمال')),
                ('car_hour_price', models.IntegerField(default=0, verbose_name='سعر ساعة عمل الالية')),
                ('worker_hour_price', models.IntegerField(default=0, verbose_name='سعر ساعة عامل')),
                ('inner_ride_start_price', models.IntegerField(default=0, verbose_name='سعر بداية الرحلة الداخلي')),
                ('outer_ride_start_price', models.IntegerField(default=0, verbose_name='سعر بداية الرحلة الخارجي')),
                ('captain_prize', models.IntegerField(default=0, verbose_name='مكافئة السائق')),
                ('mandob_prize', models.IntegerField(default=0, verbose_name='مكافئة المندوب')),
                ('late_loading_price', models.IntegerField(default=0, verbose_name='غرامة التاخير بالتحميل')),
                ('late_loading_days', models.IntegerField(default=0, verbose_name='عدد ايام التاخير بالتحميل')),
                ('late_delivering_price', models.IntegerField(default=0, verbose_name='غرامة التاخير بالتفريغ')),
                ('late_delivering_days', models.IntegerField(default=0, verbose_name='عدد ايام التاخير بالتفريغ')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة القاطرة ١')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة القاطرة ٢')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة القاطرة ٣')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('car_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carcategory', verbose_name='فئة السيارة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('goods_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goodstype', verbose_name='نوع الحمولة')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('from_prec', models.FloatField(default=0, verbose_name='النسبة من')),
                ('to_prec', models.FloatField(default=0, verbose_name='النسبة الى')),
                ('inner_ride_start_price', models.IntegerField(default=0, verbose_name='سعر بداية الرحلة الداخلي')),
                ('outer_ride_start_price', models.IntegerField(default=0, verbose_name='سعر بداية الرحلة الخارجي')),
                ('company_prec', models.FloatField(default=0, verbose_name='نسبة الشركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='PrePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب')], default='mandob', max_length=200, verbose_name='نوع المستخدم')),
                ('code', models.CharField(max_length=200, verbose_name='الكود')),
                ('amount', models.IntegerField(default=0, verbose_name='القيمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق')),
            ],
        ),
    ]
