# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverycompany', '0001_initial'),
        ('core', '0001_initial'),
        ('user', '0001_initial'),
        ('captain', '0002_initial'),
        ('mandob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaid',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل'),
        ),
        migrations.AddField(
            model_name='prepaid',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='prepaid',
            name='mandob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AddField(
            model_name='prepaid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='الزبون'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permission',
            field=models.ManyToManyField(to='core.permission', verbose_name='الصلاحيات'),
        ),
        migrations.AddField(
            model_name='pay',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='pay',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل'),
        ),
        migrations.AddField(
            model_name='pay',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='pay',
            name='mandob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AddField(
            model_name='pay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='notification',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل'),
        ),
        migrations.AddField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='notification',
            name='mandob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='الزبون'),
        ),
        migrations.AddField(
            model_name='language',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='info',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='country',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carsize',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carcompany', verbose_name='شركة السيارة'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carletter',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carcompany',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carcolor',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='car',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model_captain', to='captain.captain', verbose_name='السائق'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carcategory', verbose_name='فئة السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carcolor', verbose_name='لون السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carcompany', verbose_name='شركة السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carletter', verbose_name='حرف السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carmodel', verbose_name='موديل السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carsize', verbose_name='حجم السيارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model_company', to='deliverycompany.deliverycompany', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='car',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='car',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='car',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trailer', verbose_name='القاطرة'),
        ),
        migrations.AddField(
            model_name='blog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='banner',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='admin',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='admin',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_manager', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول'),
        ),
        migrations.AddField(
            model_name='admin',
            name='permission_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.permissiongroup', verbose_name='الصلاحيات'),
        ),
    ]
