# Generated by Django 4.2.23 on 2025-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='باركود'),
        ),
    ]
