# Generated by Django 4.2.23 on 2025-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='مسؤول مندوبين ؟'),
        ),
    ]
