# Generated by Django 4.2.23 on 2025-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admin_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب'), ('admin', 'لوحة تحكم')], max_length=200, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='user_type',
            field=models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب'), ('admin', 'لوحة تحكم')], default='mandob', max_length=200, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='user_type',
            field=models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب'), ('admin', 'لوحة تحكم')], default='mandob', max_length=200, verbose_name='نوع المستخدم'),
        ),
    ]
