# Generated by Django 4.2.23 on 2025-07-29 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycompany', '0003_deliverycompany_device_id_deliverycompany_is_logged'),
        ('user', '0004_user_device_id_user_is_logged'),
        ('captain', '0006_captain_device_id_captain_is_logged'),
        ('mandob', '0019_mandob_device_id_mandob_is_logged_and_more'),
        ('core', '0005_alter_notification_user_type_alter_pay_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client1', 'زبون عادي'), ('client2', 'زبون تاجر'), ('captain', 'سائق'), ('deliveryCompany', 'شركة نقل'), ('mandob', 'مندوب'), ('admin', 'لوحة تحكم')], default='mandob', max_length=200, verbose_name='نوع المستخدم')),
                ('amount', models.IntegerField(default=0, verbose_name='القيمة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('mandob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandob.mandob', verbose_name='المندوب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='المستخدم')),
            ],
        ),
    ]
