# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='الهاتف')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('city', models.CharField(max_length=200, verbose_name='المدينة')),
                ('location', models.CharField(max_length=200, verbose_name='العنوان')),
                ('registration_fee', models.IntegerField(default=0, verbose_name='اجور التسجيل')),
                ('salary', models.IntegerField(default=0, verbose_name='الراتب')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='اوقات العمل ( من )')),
                ('shift_stop', models.TimeField(blank=True, null=True, verbose_name='اوقات العمل ( الى )')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض')),
                ('radius', models.IntegerField(blank=True, default=0, null=True, verbose_name='نصف القطر ( بالامتار )')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extra.user_content_file_name, verbose_name='الصورة')),
                ('id_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ١')),
                ('id_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ٢')),
                ('resident_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='بطاقة السكن ١')),
                ('resident_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='بطاقة السكن ٢')),
                ('attachment1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ١')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٢')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول')], default='pending', max_length=200, verbose_name='حالة المندوب')),
                ('balance', models.IntegerField(default=0, verbose_name='الرصيد')),
                ('pin', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandob_owner', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('app_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language', verbose_name='لغة التطبيق')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='المحافظة')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', extra.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='السؤال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('type', models.CharField(choices=[('day', 'دوري'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي')], default='day', max_length=200, verbose_name='نوع الاستبيان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('mandob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mandob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandob.mandob')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.room')),
            ],
        ),
        migrations.CreateModel(
            name='MandobToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_mandob', to='mandob.mandob', verbose_name='mandob')),
            ],
            options={
                'verbose_name': 'seller Token',
                'verbose_name_plural': 'sellers Tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('captain', 'سائق'), ('user', 'زبون'), ('company', 'تاجر'), ('deliverycompany', 'ناقل'), ('car', 'سيارة')], max_length=200, verbose_name='')),
                ('barcode', models.CharField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('mandob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='اليوم')),
                ('attend_time', models.TimeField(verbose_name='تاريخ البدآ')),
                ('leave_time', models.TimeField(verbose_name='تاريخ الانتهاء')),
                ('work_hour', models.IntegerField(default=0, verbose_name='وقت العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('mandob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='جواب نصي')),
                ('answer2', models.BooleanField(default=False, verbose_name='نعم؟')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='مرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.question', verbose_name='السؤال')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.report', verbose_name='الاستبيان')),
            ],
        ),
    ]
