# Generated by Django 4.2.23 on 2025-07-16 18:01

from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('location', models.CharField(max_length=200, verbose_name='')),
                ('total_price', models.IntegerField(default=0, verbose_name='')),
                ('note', models.TextField(blank=True, null=True, verbose_name='')),
                ('file', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='barcode',
            field=models.CharField(max_length=200, unique=True, verbose_name='الباركو'),
        ),
        migrations.AlterField(
            model_name='history',
            name='mandob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('captain', 'سائق'), ('user', 'زبون'), ('company', 'تاجر'), ('deliverycompany', 'ناقل'), ('car', 'سيارة')], max_length=200, verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='OrderReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('category', models.CharField(max_length=200, verbose_name='')),
                ('type', models.CharField(choices=[('sell', 'بيع'), ('buy', 'شراء'), ('maintain', 'صيانة'), ('service', 'خدمة')], default='sell', max_length=200, verbose_name='')),
                ('count', models.IntegerField(default=1, verbose_name='')),
                ('price', models.IntegerField(default=0, verbose_name='')),
                ('paid', models.IntegerField(default=0, verbose_name='')),
                ('total_price', models.IntegerField(default=0, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.orderreport')),
            ],
        ),
    ]
