# Generated by Django 4.2.23 on 2025-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0002_orderreport_alter_history_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='latitude2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول الحالي'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='longitude2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض الحالي'),
        ),
    ]
