# Generated by Django 4.2.23 on 2025-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0003_mandob_latitude2_mandob_longitude2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='updatedtime',
            field=models.TimeField(auto_now=True, verbose_name='وقت اخر تحديث'),
        ),
    ]
