# Generated by Django 4.2.23 on 2025-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0004_mandob_updatedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='captain_goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هدف السائقين'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='company_goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هدف الشركات'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='delivery_company_goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هدف الناقلين'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='user_goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هدف الزبائن'),
        ),
    ]
