# Generated by Django 4.2.23 on 2025-07-19 12:12

from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0005_mandob_captain_goal_mandob_company_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='mandob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='location',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='السعر الكلي'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='category',
            field=models.CharField(max_length=200, verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='price',
            field=models.IntegerField(default=0, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='السعر الكلي'),
        ),
        migrations.AlterField(
            model_name='orderreportitem',
            name='type',
            field=models.CharField(choices=[('sell', 'بيع'), ('buy', 'شراء'), ('maintain', 'صيانة'), ('service', 'خدمة')], default='sell', max_length=200, verbose_name='النوع'),
        ),
    ]
