# Generated by Django 4.2.23 on 2025-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0006_orderreport_mandob_alter_orderreport_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='car_goal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هدف المركبات'),
        ),
    ]
