# Generated by Django 4.2.23 on 2025-07-21 09:35

from django.db import migrations, models
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0007_mandob_car_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='day',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='orderreportitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('day', 'دوري'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي')], default='day', max_length=200, verbose_name='نوع الاستبيان'),
        ),
    ]
