# Generated by Django 4.2.23 on 2025-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0008_remove_report_day_remove_report_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='currency',
            field=models.CharField(choices=[('iqd', 'دينار'), ('usd', 'دولار'), ('euro', 'يورو')], default='iqd', max_length=200, verbose_name='العملة'),
        ),
    ]
