# Generated by Django 4.2.23 on 2025-07-22 11:48

from django.db import migrations, models
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0009_orderreport_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreport',
            old_name='file',
            new_name='file1',
        ),
        migrations.RenameField(
            model_name='orderreportitem',
            old_name='file',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='orderreport',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='orderreportitem',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreportitem',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreportitem',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='orderreportitem',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض'),
        ),
    ]
