# Generated by Django 4.2.23 on 2025-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0010_rename_file_orderreport_file1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreportitem',
            name='paid',
        ),
        migrations.AddField(
            model_name='orderreport',
            name='last',
            field=models.IntegerField(default=0, verbose_name='المتبقي'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='المدفوع'),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='type',
            field=models.CharField(choices=[('now', 'نقد'), ('later', 'اجل')], default='now', max_length=200, verbose_name='النوع'),
        ),
    ]
