# Generated by Django 4.2.23 on 2025-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0011_remove_orderreportitem_paid_orderreport_last_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer2',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا')], default='text', max_length=200, verbose_name='نوع السؤال'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا')], default='text', max_length=200, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(verbose_name='جواب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('day', 'دوري'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي')], max_length=200, verbose_name='نوع التقرير'),
        ),
    ]
