# Generated by Django 4.2.23 on 2025-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0012_remove_answer_answer2_answer_answer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='عمل خارجي'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('day', 'يومي'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي'), ('custom', 'استبياني')], max_length=200, verbose_name='نوع التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('day', 'يومي'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي'), ('custom', 'استبياني')], default='day', max_length=200, verbose_name='نوع الاستبيان'),
        ),
    ]
