# Generated by Django 4.2.23 on 2025-07-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0013_mandob_is_free_alter_question_type_alter_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=200, verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا')], default='text', max_length=200, verbose_name='نوع الجواب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('day', 'يومي'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي'), ('custom', 'استبياني')], default='day', max_length=200, verbose_name='نوع التقرير'),
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('mandob', 'المندوبين'), ('captain', 'السائقين'), ('company', 'الناقلين')], max_length=200, verbose_name='الفئة المستهدفة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('mandob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='mandob')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='custom_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandob.customreport'),
        ),
    ]
