# Generated by Django 4.2.23 on 2025-07-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0014_alter_answer_question_alter_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='mandob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا')], default='text', max_length=200, verbose_name='نوع السؤال'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الخيار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mandob.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'خيار السؤال',
                'verbose_name_plural': 'خيارات الأسئلة',
                'ordering': ['order', 'created'],
                'unique_together': {('question', 'choice_text')},
            },
        ),
    ]
