# Generated by Django 4.2.23 on 2025-07-24 16:15

from django.db import migrations, models
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0015_alter_customreport_mandob_alter_question_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.AddField(
            model_name='answer',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='report',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات'),
        ),
    ]
