# Generated by Django 4.2.23 on 2025-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0016_remove_answer_image_answer_file1_answer_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='latitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول للمنزل'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='longitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض للمنزل'),
        ),
    ]
