# Generated by Django 4.2.23 on 2025-07-26 13:11

from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0017_mandob_latitude_base_mandob_longitude_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا'), ('choice', 'اختيار متعدد')], default='text', max_length=200, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا'), ('choice', 'اختيار متعدد')], default='text', max_length=200, verbose_name='نوع السؤال'),
        ),
        migrations.CreateModel(
            name='CustomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='السؤال')),
                ('answer_type', models.CharField(choices=[('text', 'نصي'), ('bool', 'نعم/كلا'), ('choice', 'اختيار متعدد')], default='text', max_length=200, verbose_name='نوع السؤال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('file1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات')),
                ('file2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات')),
                ('file3', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات')),
                ('file4', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات')),
                ('file5', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('custom_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.customreport', verbose_name='الاستبيان')),
                ('mandob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='mandob')),
            ],
        ),
    ]
