# Generated by Django 4.2.23 on 2025-07-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0018_alter_answer_answer_type_alter_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandob',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='is_logged',
            field=models.BooleanField(default=False, verbose_name='Is Logged'),
        ),
        migrations.AlterField(
            model_name='customanswer',
            name='mandob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandob.mandob', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(choices=[('day', 'يومي'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي')], default='day', max_length=200, verbose_name='نوع التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('day', 'يومي'), ('week', 'اسبوعي'), ('month', 'شهري'), ('year', 'سنوي')], default='day', max_length=200, verbose_name='نوع الاستبيان'),
        ),
    ]
