# Generated by Django 4.2.23 on 2025-07-29 16:27

from django.db import migrations, models
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0019_mandob_device_id_mandob_is_logged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_hour',
            field=models.IntegerField(default=0, verbose_name='وقت التأخير'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='late_cost',
            field=models.IntegerField(default=0, verbose_name='غرامة التآخير على كل ساعة'),
        ),
        migrations.AddField(
            model_name='mandob',
            name='late_hour',
            field=models.IntegerField(default=0, verbose_name='سماحية التآخير'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='attachment1',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ١'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='attachment2',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٢'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='id_doc1',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ١'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='id_doc2',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ٢'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='resident_doc1',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='بطاقة السكن ١'),
        ),
        migrations.AlterField(
            model_name='mandob',
            name='resident_doc2',
            field=models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='بطاقة السكن ٢'),
        ),
    ]
