# Generated by Django 4.2.23 on 2025-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0020_attendance_late_hour_mandob_late_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_cost',
            field=models.IntegerField(default=0, verbose_name='غرامة التآخير'),
        ),
    ]
