# Generated by Django 4.2.23 on 2025-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0023_section_employee_section_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandob',
            name='late_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سماحية التآخير'),
        ),
    ]
