# Generated by Django 4.2.23 on 2025-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0024_alter_mandob_late_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandob',
            name='late_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='غرامة التآخير على كل ساعة'),
        ),
    ]
