# Generated by Django 5.2.12 on 2026-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0025_alter_mandob_late_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandob',
            name='is_logged',
            field=models.BooleanField(default=False, verbose_name='هل المندوب مسجل دخول؟'),
        ),
    ]
