# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.IntegerField(unique=True, verbose_name='الهاتف')),
                ('id_number', models.CharField(max_length=200, verbose_name='رقم الهوية')),
                ('city', models.CharField(max_length=200, verbose_name='المدينة')),
                ('location', models.CharField(max_length=200, verbose_name='العنوان')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الصورة')),
                ('personal_id_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ١')),
                ('personal_id_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ٢')),
                ('car_id_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السنوية ١')),
                ('car_id_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السنوية ١')),
                ('agency_doc', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الوكالة')),
                ('resident_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السكن ١')),
                ('resident_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السكن ٢')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='الباركود')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة الباركود')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول')], default='pending', max_length=50, verbose_name='الحالة')),
                ('pin', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', extra.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaptainToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_captain', to='captain.captain', verbose_name='captain')),
            ],
            options={
                'verbose_name': 'seller Token',
                'verbose_name_plural': 'sellers Tokens',
                'abstract': False,
            },
        ),
    ]
