# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('captain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliverycompany', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='app_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_language', to='core.language', verbose_name='لغة التطبيق'),
        ),
        migrations.AddField(
            model_name='captain',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_captain_model', to='core.car', verbose_name='السيارة'),
        ),
        migrations.AddField(
            model_name='captain',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل'),
        ),
        migrations.AddField(
            model_name='captain',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='captain',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='captain',
            name='languages',
            field=models.ManyToManyField(to='core.language', verbose_name='اللغات'),
        ),
        migrations.AddField(
            model_name='captain',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='المحافظة'),
        ),
    ]
