# Generated by Django 4.2.23 on 2025-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='updatedtime',
            field=models.TimeField(auto_now=True, verbose_name='وقت اخر تحديث'),
        ),
    ]
