# Generated by Django 4.2.23 on 2025-07-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0003_captain_updatedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='car_id_expire',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نفاذ السنوية'),
        ),
    ]
