# Generated by Django 4.2.23 on 2025-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0004_captain_car_id_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='latitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول للمنزل'),
        ),
        migrations.AddField(
            model_name='captain',
            name='longitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض للمنزل'),
        ),
    ]
