# Generated by Django 4.2.23 on 2025-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0005_captain_latitude_base_captain_longitude_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='captain',
            name='is_logged',
            field=models.BooleanField(default=False, verbose_name='Is Logged'),
        ),
    ]
