# Generated by Django 4.2.23 on 2025-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captain', '0006_captain_device_id_captain_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='car_id_expire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ نفاذ السنوية'),
        ),
    ]
