# Generated by Django 4.2.23 on 2025-07-16 18:01

from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_barcode'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activitytype', verbose_name='نوع النشاط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_doc',
            field=models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='شهادة تآسيس الشركة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة'),
        ),
    ]
