# Generated by Django 4.2.23 on 2025-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_activity_type_alter_user_company_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول للمنزل'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض للمنزل'),
        ),
    ]
