# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverycompany', '0001_initial'),
        ('core', '0002_initial'),
        ('user', '0001_initial'),
        ('captain', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_area', models.CharField(max_length=200, verbose_name='نقطة التجمع')),
                ('collection_area_details', models.TextField(blank=True, null=True, verbose_name='تفاصبل نقطة التجمع')),
                ('rejection_reason', models.CharField(max_length=200, verbose_name='سبب الالغاء')),
                ('loading_workers_count', models.IntegerField(default=0, verbose_name='عدد عمال التحميل')),
                ('loading_workers_cost', models.IntegerField(default=0, verbose_name='سعر عمال التحميل')),
                ('delivering_workers_count', models.IntegerField(default=0, verbose_name='عدد عمال التفريغ')),
                ('delivering_workers_cost', models.IntegerField(default=0, verbose_name='سعر عمال التفريغ')),
                ('distance', models.CharField(default=0, max_length=10, verbose_name='المسافة')),
                ('order_type', models.CharField(choices=[('internal', 'داخلي'), ('external', 'خارجي')], max_length=200, verbose_name='نوع الرحلة')),
                ('captain_status', models.CharField(max_length=200, verbose_name='حالة السائق')),
                ('client_status', models.CharField(max_length=200, verbose_name='حالة الزبون')),
                ('manifest', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة المنفست')),
                ('captain_doc', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة تعهد السائق')),
                ('client_doc', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة تعهد المستخدم')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('client_rating', models.IntegerField(default=0, verbose_name='تقييم المستخدم')),
                ('captain_rating', models.IntegerField(default=0, verbose_name='تقييم السائق')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='المستخدم ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliverycompany.deliverycompany', verbose_name='الناقل')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_count', models.IntegerField(default=0, verbose_name='عدد المقطورات')),
                ('goods_cost', models.IntegerField(default=0, verbose_name='قيمة البضاعة')),
                ('goods_count', models.IntegerField(default=0, verbose_name='عدد البضاعة')),
                ('goods_details', models.TextField(blank=True, null=True, verbose_name='وصف البضاعة')),
                ('before_loading_image1', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة قبل التحميل ١')),
                ('before_loading_image2', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة قبل التحميل ٢')),
                ('before_loading_image3', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة قبل التحميل ٣')),
                ('after_delivering_image1', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة بعد التفريغ ١')),
                ('after_delivering_image2', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة بعد التفريغ ٢')),
                ('after_delivering_image3', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة بعد التفريغ ٣')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('delivery_date', models.DateField(verbose_name='تاريخ الشحن')),
                ('delivery_time', models.TimeField(verbose_name='وقت الشحن')),
                ('from_name', models.CharField(max_length=200, verbose_name='من الاسم')),
                ('from_lat', models.CharField(max_length=100, verbose_name='من خط الطول')),
                ('from_long', models.CharField(max_length=100, verbose_name='من خط العرض')),
                ('to_name', models.CharField(max_length=200, verbose_name='الى الاسم')),
                ('to_lat', models.CharField(blank=True, max_length=100, null=True, verbose_name='الى خط الطول')),
                ('to_long', models.CharField(blank=True, max_length=100, null=True, verbose_name='الى خط العرض')),
                ('distance', models.CharField(default=0, max_length=10, verbose_name='المسافة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='captain.captain', verbose_name='السائق')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car', verbose_name='السيارة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('from_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_country', to='core.country', verbose_name='من الدولة')),
                ('from_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_province', to='core.province', verbose_name='من المحافظة')),
                ('goods_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.goodstype', verbose_name='نوع البضاعة')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='الشحنة')),
                ('to_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_country', to='core.country', verbose_name='الى الدولة')),
                ('to_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_province', to='core.province', verbose_name='الى المحافظة')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trailer', verbose_name='المقطورة')),
            ],
        ),
    ]
