# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.IntegerField(unique=True, verbose_name='الهاتف')),
                ('city', models.CharField(max_length=200, verbose_name='المدينة')),
                ('location', models.CharField(max_length=200, verbose_name='العنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الصورة')),
                ('id_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ١')),
                ('id_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='الهوية ٢')),
                ('resident_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السكن ١')),
                ('resident_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='السكن ٢')),
                ('company_registration', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='تسجيل الشركة')),
                ('company_doc1', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ١')),
                ('company_doc2', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٢')),
                ('company_doc3', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٣')),
                ('company_doc4', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٤')),
                ('company_doc5', models.FileField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='مرفق ٥')),
                ('barcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='باركود')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to=extra.content_file_name, verbose_name='صورة الباركود')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض')),
                ('balance', models.IntegerField(default=0, verbose_name='الرصيد')),
                ('pin', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ اخر تحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='الدولة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='المحافظة')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialty', verbose_name='التخصص')),
            ],
            options={
                'default_permissions': (),
            },
            managers=[
                ('objects', extra.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompanyToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token_delivery', to='deliverycompany.deliverycompany', verbose_name='delivery')),
            ],
            options={
                'verbose_name': 'seller Token',
                'verbose_name_plural': 'sellers Tokens',
                'abstract': False,
            },
        ),
    ]
