# Generated by Django 4.2.23 on 2025-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverycompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='latitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول للمنزل'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='longitude_base',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض للمنزل'),
        ),
    ]
